title: Taeho Blog
description: > # this means to ignore newlines until "baseurl:"
  자기소개 블로그입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://taehoum.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: Taeho Um
tagline: Student
about-description: YongMoon Highschool Student "Taeho Um"
pic: 냥.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: taeho_um@naver.com # Add your Email address
phone: 010 2887 5612 # Add your Phone number
github: taehoum # Add your Github handle
instagram: '@me._.teo' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
